// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZ3KoovbN9v6oZytWPmrLdbo87Kp1O2s',
    appId: '1:524949524658:web:35c5fd82171c05bc1b39ab',
    messagingSenderId: '524949524658',
    projectId: 'naqliatsa',
    authDomain: 'naqliatsa.firebaseapp.com',
    storageBucket: 'naqliatsa.firebasestorage.app',
    measurementId: 'G-PNQ0DFHG0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sS_6xdLpVuzASaK6_WJNaXNvFHbjLEY',
    appId: '1:524949524658:android:25fcd8c2f62234301b39ab',
    messagingSenderId: '524949524658',
    projectId: 'naqliatsa',
    storageBucket: 'naqliatsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDGkDEsvFaJGvMc5SEgTO0wwyKwmalek',
    appId: '1:524949524658:ios:2ff657d4659485431b39ab',
    messagingSenderId: '524949524658',
    projectId: 'naqliatsa',
    storageBucket: 'naqliatsa.firebasestorage.app',
    iosBundleId: 'com.example.naqliatsa',
  );

}